### ISSUE TITLE
Bug: Canvas resizes constantly by 1px

### ISSUE THREAD

**Issue by breautek** [YuniYasha/Jiggy.io#14]

**Comment by YuniYasha** [comment]
I believe this is caused by some copy/paste code in the test_apps.  This may be an opportunity to give the canvas class support to be full screen inside the actual engine code.

**Comment by breautek** [comment]
class OddBlocks extends Engine {
	    private camera: Camera;
	    private startScreen: Entity;

	    constructor() {
	        super();

	        this._onViewPortDimensionUpdate = this._onViewPortDimensionUpdate.bind(this);

	        this.viewPort.on(ViewPortEventTypes.DIMENSION_UPDATE.toString(), this._onViewPortDimensionUpdate);
	        this.viewPort.autoSize = true;

	        this.renderingEngine = new TwoDimensionalRenderingEngine();
	        this.startScreen = new StartScreen();

	        this.camera = new Camera(this.startScreen, null, {width: 250, height: 250}, null, {width: 500, height: 500});
	    }

	    private _onViewPortDimensionUpdate(event: DimensionUpdateEvent): void {
	        this.startScreen.width = event.newDimensions.width;
	        this.startScreen.height = event.newDimensions.height;
	    }
	}

The above class, will cause the canvas to grow continuously forever by 1px in height.
The expected result is for the startScreen to max the dimensions of the ViewPort.

**Comment by YuniYasha** [comment]
Ah is autoSize fullScreen?  It's been so long since I wrote that ... lol

**Comment by breautek** [comment]
@YuniYasha  Yah it has something to do with the autoSize property. Doesn't actually have anything to do with the dimension update.

While autoSize = true it is actually increasing canvas height by 2px per tick. The problem goes away if this flag is turned off.
