### ISSUE TITLE
Color class

### ISSUE THREAD

**Issue by breautek** [YuniYasha/Jiggy.io#17]
A class that represents colors.

The engine, based on the Color interface seems to work with an {r,g,b} objects, it would be nice to have a Color class that not only accepts RGB values, but also accepts other formats.

it could have static methods such as
`Color.fromString(colorString: string): Color`

**Comment by YuniYasha** [comment]
I think this is a good idea.  fromString, fromHex, fromRGB, as well as "to" methods, potentionally, on an instance.

**Comment by breautek** [comment]
Yah, we have a number of instances where I see color properties but they are all looking for a string.

Entity and the TextAssetBuilder are a couple that comes to mind. I think they are should be updated to use the Class object, and then they serialize it using one of the serializer methods as necessary.

A color instance could also house a few other helper methods to modify colours, such as lighten or darken by a certain percentage.

**Comment by breautek** [comment]
The "to" methods would definitely be required on an instance. They couldn't be static methods.

The constructor could optionally accept 4 parameters: r,g,b,a. With the default being 0,0,0,1 being a transparent color. Or if you use one of the static "from" methods, it will simply parse out the color information, and return an instance of Color with the appropriate color.
